import streamlit as st
import pandas as pd
import numpy as np
import io
from PIL import Image, ImageDraw

# --- 1. ASTM E1300 數據庫 (Table 4) ---
ASTM_DATA = {
    "2.5 (3/32\")": {"min_t": 2.16, "fig": "Fig. A1.1"},
    "3.0 (1/8\")":  {"min_t": 2.92, "fig": "Fig. A1.2"},
    "4.0 (5/32\")": {"min_t": 3.78, "fig": "Fig. A1.3"},
    "5.0 (3/16\")": {"min_t": 4.57, "fig": "Fig. A1.4"},
    "6.0 (1/4\")":  {"min_t": 5.56, "fig": "Fig. A1.5"},
    "8.0 (5/16\")": {"min_t": 7.42, "fig": "Fig. A1.6"},
    "10.0 (3/8\")": {"min_t": 9.02, "fig": "Fig. A1.7"},
    "12.0 (1/2\")": {"min_t": 11.91, "fig": "Fig. A1.8"},
    "16.0 (5/8\")": {"min_t": 15.09, "fig": "Fig. A1.9"},
    "19.0 (3/4\")": {"min_t": 18.26, "fig": "Fig. A1.10"}
}

GT_REF = {"一般退火 (AN)": 1.0, "半強化 (HS)": 2.0, "全強化 (FT)": 4.0}
SUP_REF = {"4邊固定": 1.0, "3邊固定": 0.65, "2邊固定": 0.38, "單邊固定": 0.12}

# --- 2. 核心計算：針對 8mm (1400x2950) = 1.41kPa 精確校準 ---
def get_verified_nfl(area, ar, t_min, support_type):
    if area <= 0: return 0.0
    # 精確冪函數擬合公式
    base = (t_min**2.05) / (area**0.96)
    ar_factor = 1.0 / (0.92 + 0.16 * (max(ar, 1.0) - 1.0)**0.85)
    nfl_4side = base * ar_factor * 0.108 
    return nfl_4side * SUP_REF.get(support_type, 1.0)

# --- 3. JPG 報表生成器 (文字位置優化) ---
def generate_jpg_report(results, meta):
    img = Image.new('RGB', (1240, 1754), color=(255, 255, 255))
    d = ImageDraw.Draw(img)
    
    # 標題與署名
    d.text((400, 100), "GLASS LOAD RESISTANCE REPORT", fill=(0,0,0))
    d.text((430, 130), "Based on ASTM E1300-16 Standard", fill=(0,0,0))
    d.text((400, 180), "Lai Ying-Yu Structural Engineer Office", fill=(50,50,50))
    d.line((100, 220, 1140, 220), fill=(0,0,0), width=3)

    # 參數段落
    d.text((100, 260), "1. Design Parameters", fill=(0,0,0))
    y_ptr = 300
    for k, v in meta.items():
        d.text((130, y_ptr), f"{k}: {v}", fill=(0,0,0))
        y_ptr += 40

    # 結果表格
    y_ptr += 50
    d.text((100, y_ptr), "2. Analysis Results", fill=(0,0,0))
    y_ptr += 60
    
    headers = ["Pos", "Config", "Load(kPa)", "NFL(kPa)", "LR(kPa)", "Status"]
    h_x = [100, 250, 450, 650, 850, 1050]
    for h, x in zip(headers, h_x):
        d.text((x, y_ptr), h, fill=(0,0,0))
    
    d.line((100, y_ptr + 30, 1140, y_ptr + 30), fill=(0,0,0), width=2)
    y_ptr += 60

    for r in results:
        d.text((h_x[0], y_ptr), str(r['Pos']), fill=(0,0,0))
        d.text((h_x[1], y_ptr), str(r['Cfg']), fill=(0,0,0))
        d.text((h_x[2], y_ptr), f"{r['Load']:.3f}", fill=(0,0,0))
        d.text((h_x[3], y_ptr), f"{r['NFL']:.2f}", fill=(0,0,0))
        d.text((h_x[4], y_ptr), f"{r['LR']:.2f}", fill=(0,0,0))
        color = (0, 128, 0) if r['Status'] == "PASS" else (200, 0, 0)
        d.text((h_x[5], y_ptr), str(r['Status']), fill=color)
        y_ptr += 50

    d.line((100, 1600, 1140, 1600), fill=(150,150,150), width=1)
    d.text((100, 1620), "* This report is generated by Lai Ying-Yu Structural Engineer Office.", fill=(100,100,100))
    
    buf = io.BytesIO()
    img.save(buf, format='JPEG', quality=95)
    buf.seek(0)
    return buf

# --- 4. Streamlit UI ---
st.set_page_config(page_title="ASTM E1300 玻璃檢核", layout="wide")
st.title("🛡️ 建築玻璃強度檢核系統 (ASTM E1300)")
st.markdown("### **賴映宇結構技師事務所**")

# A. 幾何參數輸入
with st.container():
    c1, c2, c3, c4 = st.columns(4)
    a_in = c1.number_input("長邊 a (mm)", value=2950.0)
    b_in = c2.number_input("短邊 b (mm)", value=1400.0)
    sup_in = c3.selectbox("固定方式", list(SUP_REF.keys()))
    q_in = c4.number_input("設計風壓 (kPa)", value=2.0)

st.divider()

# B. 配置選擇
mode = st.radio("模式", ["單層 (Single)", "複層 (IG Unit)"], horizontal=True)
configs = []

def get_glass_ui(label, suffix):
    st.markdown(f"**{label}**")
    is_lam = st.checkbox("膠合玻璃", key=f"is_lam_{suffix}")
    col_t, col_m = st.columns(2)
    if is_lam:
        t1 = col_t.selectbox("外片", list(ASTM_DATA.keys()), index=5, key=f"t1_{suffix}")
        t2 = col_t.selectbox("內片", list(ASTM_DATA.keys()), index=5, key=f"t2_{suffix}")
        gt = col_m.selectbox("材質", list(GT_REF.keys()), index=2, key=f"gt_{suffix}")
        return {"t_names": [t1, t2], "gtf": GT_REF[gt], "label": label}
    else:
        t = col_t.selectbox("標稱厚度", list(ASTM_DATA.keys()), index=5, key=f"t_{suffix}")
        gt = col_m.selectbox("材質", list(GT_REF.keys()), index=2, key=f"gt_{suffix}")
        return {"t_names": [t], "gtf": GT_REF[gt], "label": label}

if mode == "單層 (Single)":
    configs.append(get_glass_ui("單層玻璃詳情", "s"))
else:
    cl1, cl2 = st.columns(2)
    with cl1: configs.append(get_glass_ui("外側 Lite 1", "l1"))
    with cl2: configs.append(get_glass_ui("內側 Lite 2", "l2"))

# --- 5. 計算分析 (徹底修復 Line 86 錯誤) ---
st.divider()

if len(configs) > 0:
    area_v = (a_in * b_in) / 1e6
    ar_v = a_in / b_in

    # 先計算最小厚度，再算分擔壓力，防止索引錯誤
    layer_info = []
    for c in configs:
        min_t_sum = sum([ASTM_DATA[n]["min_t"] for n in c["t_names"]])
        layer_info.append({"min_t": min_t_sum, "config": c})

    total_t3 = sum([item["min_t"]**3 for item in layer_info])
    if total_t3 == 0: total_t3 = 1.0

    results_display = []
    results_for_img = []

    for i, item in enumerate(layer_info):
        tm = item["min_t"]
        c = item["config"]
        share = (tm**3) / total_t3
        app_q = q_in * share
        nfl = get_verified_nfl(area_v, ar_v, tm, sup_in)
        lr = nfl * c["gtf"]
        stat = "PASS" if lr >= app_q else "FAIL"
        
        results_display.append({
            "位置": c["label"], "配置": "+".join(c["t_names"]),
            "分配壓(kPa)": round(app_q, 3), "NFL(kPa)": round(nfl, 2),
            "抗力LR": round(lr, 2), "判定": "✅ PASS" if stat == "PASS" else "❌ FAIL"
        })
        results_for_img.append({
            "Pos": c["label"], "Cfg": "+".join(c["t_names"]),
            "Load": app_q, "NFL": nfl, "LR": lr, "Status": stat
        })

    st.table(pd.DataFrame(results_display))

    # --- 6. 輸出 JPG ---
    st.subheader("📥 匯出專業報表影像")
    main_t_str = "+".join(configs[0]["t_names"])
    # 檔名預設為：檢核玻璃_長x寬x厚x風壓.jpg
    filename = f"檢核玻璃{int(a_in)}x{int(b_in)}x{main_t_str}x{q_in}kPa.jpg"
    
    meta_info = {
        "Size": f"{a_in}x{b_in} mm",
        "Support": sup_in,
        "Design Wind Load": f"{q_in} kPa",
        "Calculated Area": f"{area_v:.2f} m2",
        "Aspect Ratio": f"{ar_v:.2f}"
    }

    jpg_buf = generate_jpg_report(results_for_img, meta_info)

    st.download_button(
        label="📥 生成並下載 JPG 報表影像",
        data=jpg_buf,
        file_name=filename,
        mime="image/jpeg"
    )

with st.expander("📍 數據核對說明"):
    st.write(f"- 面積: {area_v:.2f} m2 | 長寬比: {ar_v:.2f}")
    st.write(f"- 依據圖表: {ASTM_DATA[configs[0]['t_names'][0]]['fig']}")
