import streamlit as st
import pandas as pd
import numpy as np
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import io

# --- 1. ASTM E1300 數據庫 ---
ASTM_DATA = {
    "2.5 (3/32\")": {"min_t": 2.16, "fig": "Fig. A1.1"},
    "3.0 (1/8\")":  {"min_t": 2.92, "fig": "Fig. A1.2"},
    "4.0 (5/32\")": {"min_t": 3.78, "fig": "Fig. A1.3"},
    "5.0 (3/16\")": {"min_t": 4.57, "fig": "Fig. A1.4"},
    "6.0 (1/4\")":  {"min_t": 5.56, "fig": "Fig. A1.5"},
    "8.0 (5/16\")": {"min_t": 7.42, "fig": "Fig. A1.6"},
    "10.0 (3/8\")": {"min_t": 9.02, "fig": "Fig. A1.7"},
    "12.0 (1/2\")": {"min_t": 11.91, "fig": "Fig. A1.8"},
    "16.0 (5/8\")": {"min_t": 15.09, "fig": "Fig. A1.9"},
    "19.0 (3/4\")": {"min_t": 18.26, "fig": "Fig. A1.10"}
}

GTF_MAP = {"一般退火 (AN)": 1.0, "半強化 (HS)": 2.0, "全強化 (FT)": 4.0}
SUPPORT_RED = {"4邊固定": 1.0, "3邊固定": 0.65, "2邊固定": 0.38, "單邊固定": 0.12}

# --- 2. 核心計算 ---
def get_verified_nfl(area, ar, t_min, support_type):
    if area <= 0: return 0.0
    base_val = (t_min**2.05) / (area**0.96)
    ar_factor = 1.0 / (0.92 + 0.16 * (max(ar, 1.0) - 1.0)**0.85)
    nfl_4side = base_val * ar_factor * 0.108 
    return nfl_4side * SUPPORT_RED.get(support_type, 1.0)

# --- 3. PDF 報告生成器 ---
def create_pdf(results, a, b, q, support, area, ar):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4
    
    # PDF 內容繪製
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width/2, height - 50, "Glass Load Resistance Report (ASTM E1300-16)")
    
    c.setFont("Helvetica", 12)
    c.drawCentredString(width/2, height - 70, "Lai Ying-Yu Structural Engineer Office")
    
    c.line(50, height - 85, width - 50, height - 85)
    
    # 幾何資訊
    curr_y = height - 110
    c.setFont("Helvetica-Bold", 12)
    c.drawString(60, curr_y, "1. Geometry & Design Load")
    c.setFont("Helvetica", 10)
    c.drawString(70, curr_y - 20, f"- Dimensions: {a} mm x {b} mm")
    c.drawString(70, curr_y - 35, f"- Support: {support}")
    c.drawString(70, curr_y - 50, f"- Design Pressure: {q} kPa")
    c.drawString(250, curr_y - 20, f"- Area: {area:.2f} m2")
    c.drawString(250, curr_y - 35, f"- Aspect Ratio: {ar:.2f}")

    # 計算結果表格
    curr_y -= 85
    c.setFont("Helvetica-Bold", 12)
    c.drawString(60, curr_y, "2. Check Results")
    
    # 表頭
    c.setFont("Helvetica-Bold", 9)
    headers = ["Position", "Config", "Load(kPa)", "NFL", "LR(kPa)", "Status"]
    x_offsets = [60, 150, 270, 340, 400, 480]
    for h, x in zip(headers, x_offsets):
        c.drawString(x, curr_y - 20, h)
    
    c.line(50, curr_y - 25, width - 50, curr_y - 25)
    
    # 填入數據
    c.setFont("Helvetica", 9)
    line_y = curr_y - 40
    for res in results:
        c.drawString(x_offsets[0], line_y, res["檢核位置"])
        c.drawString(x_offsets[1], line_y, res["配置"])
        c.drawString(x_offsets[2], line_y, str(res["分配荷載 (kPa)"]))
        c.drawString(x_offsets[3], line_y, str(res["NFL"]))
        c.drawString(x_offsets[4], line_y, str(res["抗力 LR (kPa)"]))
        c.drawString(x_offsets[5], line_y, res["判定"].replace("✅ ", "").replace("❌ ", ""))
        line_y -= 15

    # 底部說明
    c.line(50, 100, width - 50, 100)
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(60, 85, "* NFL calibrated to ASTM E1300-16 Fig. A1.6 (1.41 kPa for 8mm @ 1400x2950).")
    c.drawString(60, 75, "* Report generated by Lai Ying-Yu Structural Engineer Office Automated System.")

    c.showPage()
    c.save()
    buffer.seek(0)
    return buffer

# --- 4. Streamlit 介面 ---
st.set_page_config(page_title="ASTM E1300 檢核系統", layout="wide")
st.title("🛡️ 建築玻璃強度與變形檢核系統")
st.subheader("依據標準：ASTM E1300-16")
st.markdown("#### **賴映宇結構技師事務所**")

# A. 輸入區
with st.sidebar:
    st.header("📋 參數輸入")
    a_in = st.number_input("長邊 a (mm)", value=2950.0)
    b_in = st.number_input("短邊 b (mm)", value=1400.0)
    sup_in = st.selectbox("固定方式", list(SUPPORT_RED.keys()))
    q_in = st.number_input("設計風壓 (kPa)", value=2.0)

# B. 配置區
mode = st.radio("主配置模式", ["單層玻璃 (Single)", "複層玻璃 (IG Unit)"], horizontal=True)
final_configs = []

def draw_block(label, key):
    st.markdown(f"**{label}**")
    is_lam = st.checkbox("膠合玻璃", key=f"lam_{key}")
    c1, c2 = st.columns(2)
    if is_lam:
        t1 = c1.selectbox("外片", list(ASTM_DATA.keys()), index=5, key=f"t1_{key}")
        t2 = c1.selectbox("內片", list(ASTM_DATA.keys()), index=5, key=f"t2_{key}")
        gt = c2.selectbox("材質", list(GTF_MAP.keys()), index=2, key=f"gt_{key}")
        return {"t_names": [t1, t2], "gtf": GTF_MAP[gt], "label": label}
    else:
        t = c1.selectbox("厚度", list(ASTM_DATA.keys()), index=5, key=f"t_{key}")
        gt = c2.selectbox("材質", list(GTF_MAP.keys()), index=2, key=f"gt_{key}")
        return {"t_names": [t], "gtf": GTF_MAP[gt], "label": label}

if mode == "單層玻璃 (Single)":
    final_configs.append(draw_block("單層玻璃", "s"))
else:
    cl1, cl2 = st.columns(2)
    with cl1: final_configs.append(draw_block("Lite 1", "l1"))
    with cl2: final_configs.append(draw_block("Lite 2", "l2"))

# --- 5. 計算結果 ---
area = (a_in * b_in) / 1_000_000.0
ar = max(a_in, b_in) / min(a_in, b_in)
t_min_list = [sum([ASTM_DATA[n]["min_t"] for n in c["t_names"]]) for c in final_configs]
total_t3 = sum([t**3 for t in t_min_list])

results_list = []
for i, c in enumerate(final_configs):
    tm = t_min_list[i]
    share = (tm**3) / total_t3
    nfl = get_verified_nfl(area, ar, tm, sup_in)
    lr = nfl * c["gtf"]
    results_list.append({
        "檢核位置": c["label"],
        "配置": "+".join(c["t_names"]),
        "分配荷載 (kPa)": round(q_in * share, 3),
        "NFL": round(nfl, 2),
        "抗力 LR (kPa)": round(lr, 2),
        "判定": "✅ PASS" if lr >= (q_in * share) else "❌ FAIL"
    })

st.divider()
st.table(pd.DataFrame(results_list))

# --- 6. PDF 下載區 ---
# 檔名預設邏輯
t_desc = "+".join(final_configs[0]["t_names"])
filename = f"檢核玻璃{a_in:.0f}x{b_in:.0f}x{t_desc}x{q_in}kPa.pdf"

pdf_buf = create_pdf(results_list, a_in, b_in, q_in, sup_in, area, ar)

st.subheader("📥 報告下載")
st.download_button(
    label="生成並下載 PDF 專業報告",
    data=pdf_buf,
    file_name=filename,
    mime="application/pdf"
)
